# Generated by Django 2.1.3 on 2019-01-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ofice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_ofice', models.CharField(max_length=64)),
                ('name_ofice', models.CharField(max_length=64)),
                ('line_ofice', models.CharField(max_length=64)),
            ],
        ),
    ]
